Admin user
Code-Institute-Community/business-analysis-project pull request #39
Opened 2022-03-09 21:10 UTC by thanh-cao

Issues fixed: #21 Admin user able to create new organisation and edit

2022-03-11 16:48 UTC, auxfuse requested changes
Hi Thanh, thanks for the hard work gone into this. It's a big one! 🤜

The first thing we want to address is the Materialize usage. See comments throughout the PR. Once done, push those changes to the branch associated with this PR to auto-update same and then we can review again. 😀

2022-03-11 16:48 UTC, auxfuse commented on templates/base.html
> +	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
We are using Bootstrap 5 for this project.

Can you update this to reflect, and then match the utility class usage in the template files to suit Bootstrap 5 please? 😀

2022-03-11 16:48 UTC, auxfuse commented on templates/base.html
> +	<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
As above, can this be removed to suit Bootstrap inclusion? 🤜

2022-03-11 16:48 UTC, auxfuse commented on templates/create_organisation.html
> +<form class="col s12" method="POST" action="{{ url_for('organisation_create') }}">
This is an example of the utility classes that will need to be updated to suit Bootstrap usage over Materialize. Anywhere in these html files, that utilises Materialize Utility Classes will need to be updated to suit Bootstrap.

2022-03-11 19:58 UTC, thanh-cao commented
@auxfuse I have updated Materialize's cdn to Bootstrap5 and Bootstrap icons. Classes on all three templates for organisation's CRUD are also updated accordingly with bootstrap :)

2022-03-12 16:57 UTC, auxfuse commented
Hi @thanh-cao thank you for the updates 😀We've just merged another PR that has unfortunately now given your's some conflicts in the `app.py` file. Can you resolve, push and then we can merge 💯

2022-03-13 10:57 UTC, thanh-cao commented
@auxfuse I have fixed the conflicts in the app.py. Reason for conflict was that both John and I created same functionality to create new organisation BUT for 2 different user roles: admin and normal user. I have kept John's code and adjusted a mine accordingly to keep name consistency. I have left a todo note there for some discussion if we should define permission here for admin and user to be implemented later.

Made some adjustments to the templates to keep the styling consistent in both create and edit templates.
I didn't make any adjustments to company_web_scraper.py but for some reason it says on my branch that I have to commit the file so. I have checked with the content of the file on this repo and there isn't any difference between the two.

2022-03-13 18:57 UTC, auxfuse approved these changes
Everything looks great to me here! Well done @thanh-cao 🤜

2022-03-13 18:58 UTC, auxfuse approved these changes
Everything looks great to me here! Well done @thanh-cao 🤜

2022-03-13 18:58 UTC, merged