Adding analysed data and functionality to categorise in admin panel
Code-Institute-Community/business-analysis-project pull request #78
Opened 2022-08-03 11:04 UTC by stefdworschak

# Business Analysis 🟠 Code Institute 🟠 Community Project - Pull Request 🎉🎉

## Pull Request References:
#29 

## PR contains:
- Adding data including the text fetched from the websites and analysed keywords
- Adding editable field in the "Organisation" admin panel view to edit the categories

## Breaking changes
None

## Screenshots/Gifs/Media
![Screenshot from 2022-08-03 12-04-21](https://user-images.githubusercontent.com/31205982/182593243-a2af3535-2d73-4833-91b5-c98a4602da02.png)

2022-08-04 11:33 UTC, auxfuse requested changes
Lots of changes in this and lots to digest. Well done Stefan, only one change needed after a lengthy review and wrapping my head around it. That pesky EOF new line 😉

2022-08-04 11:33 UTC, auxfuse commented on data/categories.json
> +]
New line needed at EOF.

2022-08-05 10:20 UTC, stefdworschak commented on data/categories.json
> +]
Added the line.

2022-08-05 10:21 UTC, stefdworschak commented
Thanks @auxfuse for the review and the perseverance! :sweat_smile:

2022-08-05 19:13 UTC, merged